### ISSUE TITLE
Ability to get Redis connection

### ISSUE THREAD

**Issue by erkie** [digitalocean/go-workers2#17]
In the original `go-workers` it's possible to access the underlying Redis pool object with simply `workers.Config.Pool` which is an instance of `*redis.Pool`

In this project it's hidden behind hidden instance variables.

We use it to be able to run fetches for statistics, and other minor things  that doesn't (imo) motivate setting up a separate connection pool.

So an idea would be a public method to `GetRedisPool` or perhaps just expose it as a public field?

**Comment by stefannegrea** [comment]
One thing to point out is that we swapped Redis driver in this project. Any external code that you might have will need to be rewritten to use [go-redis](https://github.com/go-redis/redis).

Taking a step back I see three options, not necessarily mutually exclusive:

1. Expose the internal Redis client to the outside world (`GetRedisClient`)
   - advantage: reuse the client
   - disadvantage: performance could be impacted since redis commands would use the same connection pool as the library
    - disadvantage: external code could break the client inadvertently, impacting the flow of the library
1. Expose a method to build an identical client to the internal one (`BuildRedisClient`)
    - advantage: client and connection pool separated is not shared between internal and external code
    - advantage: identical client configuration to the internal one; no need to manually stitch configuration options
    - disadvantage: another set of connections to the Redis server
1. Expose manager stats via a public method (`GetStats`):
     - advantage: no need to access stats manually via Redis client
     - advantage: structured stats
     - disadvantage: no way to access Redis for additional commands

Which one these options do you think would be a good design choice long term? My inclination is towards implementing both 2 & 3 and keep the internal Redis client exclusive for worker operations.

Thanks for reporting this issue!

**Comment by erkie** [comment]
My vote is on just making `manager.options` public, and a `GetRedisClient` method. It feels like it would make the library easier to work with when adding new features or plugins. I can't really see how it could too much negatively affect anything unless something really bad is done in the client code, in which case it's in the client code anyway.

`3` sounds like a nice added feature, and I can see it being useful for others wanting to hook in Prometheus/Graphite monitoring or similar tools. It would basically be what the `StatsServer` does today but moved to a cleaner method. Basically just exposing `https://github.com/digitalocean/go-workers2/blob/master/stats.go#L67` that method. But I'd say it warrants its own issue in github.
